# Generated by Django 3.2 on 2023-01-08 13:02

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Имя пользователя. Не более 150 символов', max_length=150, unique=True, validators=[users.validators.username_validator], verbose_name='Имя пользователя'),
        ),
    ]
