# Generated by Django 3.2 on 2023-01-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230110_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(editable=False, max_length=255, null=True, unique=True),
        ),
    ]
