# Generated by Django 3.2 on 2023-01-04 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256, validators=[django.core.validators.MaxLengthValidator(256)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('^[-a-zA-Z0-9_]+$')]),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=256, validators=[django.core.validators.MaxLengthValidator(256)]),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('^[-a-zA-Z0-9_]+$')]),
        ),
    ]
