# Generated by Django 3.2.16 on 2023-01-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_score'),
        ('reviews', '0007_auto_20230105_0152'),
    ]

    operations = [
    ]
